proxmox = {type = "A", value = "10.175.225.254"}
docs = {type = "A", value = "10.175.225.243"}
ctfd = {type = "A", value = "10.175.225.241"}

guac = {type = "A", value = "10.175.225.242"}


nextcloud = {type = "A", value = "10.175.225.252"}
"_acme-challenge.nextcloud" = {type = "TXT", value = "-4EBa301-8tQ9Uhjp4jCT-GzOLoCGQ8_Xyccj4Duns8"}

pnet = {type = "A", value = "10.175.225.253"}
kasm = {type = "A", value = "10.175.225.251"}

auth = {type = "A", value = "10.175.225.249"}
"_acme-challenge.auth" = {type = "TXT", value = "uJFQMiKq4F5LYnR4yz4eYC8N7jbWePvOvKGBjfFNOIw"}

www = {type = "CNAME", value = "wsg-csg.github.io."}

[["@"]]
type = "A"
values = ['185.199.108.153', '185.199.109.153', '185.199.110.153', '185.199.111.153']

[["@"]]
type = "TXT"
value = "hullo there hacker"
